const NEPALESE = {
  fields: [
    {
      field_name: "Computer Science and Information Systems",
      universities: [
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name: "Kathmandu University (KU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2000,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Local Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Business and Management Studies",
      universities: [
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Finance (Accounting and Finance)",
      universities: [
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name: "Tribhuvan University (TU) - Faculty of Management",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1500,
          acceptance_rate_percent: 45,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Semester-wise Performance Awards",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Economics and Econometrics",
      universities: [
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name:
            "Tribhuvan University (TU) - Central Department of Economics",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 50,
          scholarships_and_grants: [
            "TU Merit Scholarships",
            "Government Quota Scholarships",
            "Research Fellowships",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized tuition",
            "Installment payment options",
            "Government grants",
          ],
          accommodation_and_facilities: [
            "University halls",
            "Central Library",
            "Student Unions",
            "Canteen and sports facilities",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Data Science and Artificial Intelligence",
      universities: [
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name: "Kathmandu University (KU) - School of Engineering",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 2200,
          acceptance_rate_percent: 20,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
            "Industry-sponsored Scholarships",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Graduate Assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Advanced AI research labs",
            "Central Library",
            "Student support services",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Nursing",
      universities: [
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name:
            "Tribhuvan University (IOM) / B.P. Koirala Institute of Health Sciences (BPKIHS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 8000,
          acceptance_rate_percent: 5,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Special Nursing Grants",
          ],
          financial_burden_reduction_policies: [
            "Subsidized fees for quota students",
            "Installment payments",
            "Stipends for clinical practice",
          ],
          accommodation_and_facilities: [
            "Mandatory campus hostels",
            "Clinical training in university hospitals",
            "Specialized nursing labs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Medicine",
      universities: [
        {
          university_name: "Institute of Medicine (IOM)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "BPKIHS Dharan",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "PAHS Lalitpur",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name:
            "Kathmandu University School of Medical Sciences (KUSMS)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name: "Gandaki Medical College",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name: "Tribhuvan University (Institute of Medicine - IOM)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name: "Tribhuvan University (Institute of Medicine - IOM)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name: "Tribhuvan University (Institute of Medicine - IOM)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name: "Tribhuvan University (Institute of Medicine - IOM)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name: "Tribhuvan University (Institute of Medicine - IOM)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 12000,
          acceptance_rate_percent: 3,
          scholarships_and_grants: [
            "Government Quota Scholarships",
            "Institutional Merit Scholarships",
            "Research Grants",
          ],
          financial_burden_reduction_policies: [
            "Highly subsidized fees for quota students",
            "Installment payments",
            "Hospital-based work-study",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Teaching hospitals",
            "Research labs",
            "Medical libraries",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Engineering and Technology (Broad)",
      universities: [
        {
          university_name: "Tribhuvan University (IOE) - Pulchowk Campus",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "Tribhuvan University (IOE) - Thapathali Campus",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "Tribhuvan University (IOE) - Paschimanchal Campus",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name: "Tribhuvan University (IOE) - Purwanchal Campus",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name:
            "Tribhuvan University (IOE) - Chitwan Engineering College",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name:
            "Tribhuvan University (Institute of Engineering - IOE)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name:
            "Tribhuvan University (Institute of Engineering - IOE)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name:
            "Tribhuvan University (Institute of Engineering - IOE)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name:
            "Tribhuvan University (Institute of Engineering - IOE)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name:
            "Tribhuvan University (Institute of Engineering - IOE)",
          country: "Nepal",
          admission_difficulty_score: 9,
          average_annual_tuition_usd: 3000,
          acceptance_rate_percent: 10,
          scholarships_and_grants: [
            "IOE Merit Scholarships",
            "Regular (Subsidized) Seats",
            "Government Quotas",
          ],
          financial_burden_reduction_policies: [
            "Subsidized seats for top rankers",
            "Installment payment options",
            "Student loans",
          ],
          accommodation_and_facilities: [
            "Campus hostels",
            "Advanced engineering labs",
            "Central Library",
            "Robotics and innovation clubs",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Agriculture and Forestry",
      universities: [
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name: "Agriculture and Forestry University (AFU)",
          country: "Nepal",
          admission_difficulty_score: 7,
          average_annual_tuition_usd: 1200,
          acceptance_rate_percent: 25,
          scholarships_and_grants: [
            "Government Scholarships",
            "AFU Merit Awards",
            "Research Assistantships",
          ],
          financial_burden_reduction_policies: [
            "Subsidized tuition",
            "Research grants",
            "Installment payment options",
          ],
          accommodation_and_facilities: [
            "On-campus housing",
            "Agricultural farms",
            "Forestry labs",
            "Research centers",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
    {
      field_name: "Environmental Sciences",
      universities: [
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 1,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 2,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 3,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 4,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 5,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 6,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 7,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 8,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 9,
        },
        {
          university_name: "Kathmandu University (KU) - School of Science",
          country: "Nepal",
          admission_difficulty_score: 6,
          average_annual_tuition_usd: 1800,
          acceptance_rate_percent: 35,
          scholarships_and_grants: [
            "Merit-based Scholarship",
            "Need-based Scholarship",
            "UGC Formula Funding Scholarship",
          ],
          financial_burden_reduction_policies: [
            "Installment payment options",
            "Education loan (25-50% coverage)",
            "Teaching assistantships",
          ],
          accommodation_and_facilities: [
            "On-campus dormitories",
            "Environmental research labs",
            "Central Library",
            "Field research stations",
          ],
          ranking_source: "Nepal University Rankings 2024 (Local Evaluation)",
          rank: 10,
        },
      ],
    },
  ],
};
